--Create triggers that TIMESTAMP all the transactions in INBOX/OUTBOX/FAILED/ACK (look at p.37)

CREATE OR REPLACE EDITIONABLE TRIGGER  "PF_PO_INBOX_IN_DATE_TIME_TRIGGER" 
BEFORE 
INSERT ON "PF_PO_INBOX" 
FOR EACH ROW
BEGIN
:NEW."IN_DATE" := TO_CHAR(SYSDATE, 'YYYYMMDD'); 
:NEW."IN_TIME" := TO_CHAR(SYSDATE, 'HHMISS'); 
END;

CREATE OR REPLACE EDITIONABLE TRIGGER  "PF_PO_OUTBOX_IN_DATE_TIME_TRIGGER" 
BEFORE 
INSERT ON "PF_PO_OUTBOX" 
FOR EACH ROW
BEGIN
:NEW."IN_DATE" := TO_CHAR(SYSDATE, 'YYYYMMDD'); 
:NEW."IN_TIME" := TO_CHAR(SYSDATE, 'HHMISS'); 
END;

CREATE OR REPLACE EDITIONABLE TRIGGER  "PF_PO_FAILED_IN_DATE_TIME_TRIGGER" 
BEFORE 
INSERT ON "PF_PO_FAILED" 
FOR EACH ROW
BEGIN
:NEW."IN_DATE" := TO_CHAR(SYSDATE, 'YYYYMMDD'); 
:NEW."IN_TIME" := TO_CHAR(SYSDATE, 'HHMISS'); 
END;

INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'KAR', 'Create timestamp triggers', 'Create triggers that TIMESTAMP all the transactions in INBOX/OUTBOX/FAILED.')
