--Create triggers that TIMESTAMP all the transactions in INBOX/OUTBOX/FAILED/ACK (look at p.37)

CREATE OR REPLACE EDITIONABLE TRIGGER  "PF_ACK_OUTBOX_I_DATE_TIME_TRIGGER" 
BEFORE 
INSERT ON "PF_ACK_INBOX" 
FOR EACH ROW
BEGIN
:NEW."IN_DATE" := TO_CHAR(SYSDATE, 'YYYYMMDD'); 
:NEW."IN_TIME" := TO_CHAR(SYSDATE, 'HHMISS'); 
END;

CREATE OR REPLACE EDITIONABLE TRIGGER  "PF_ACK_OUTBOX_O_DATE_TIME_TRIGGER" 
BEFORE 
INSERT ON "PF_ACK_OUTBOX" 
FOR EACH ROW
BEGIN
:NEW."IN_DATE" := TO_CHAR(SYSDATE, 'YYYYMMDD'); 
:NEW."IN_TIME" := TO_CHAR(SYSDATE, 'HHMISS'); 
END;


INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'MAT', 'Create timestamp triggers for ACKS', 'Create triggers that TIMESTAMP all the transactions in ACKS.')
