INSERT INTO PF_BANKACCOUNTS_TRANSACTIONS (PO_ID, ACCOUNT_ID, BANK_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_PURPOSE, TRANSACTION_AMOUNT) SELECT ID, ACCOUNT_ID, BANK_ID, INIT_DATE, INIT_TIME, 'Initialization', AMOUNT FROM PF_BANKACCOUNTS_INIT;

--Log
INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'KAR', 'Rinitialize transactions.', 'Reinitialized bank transactions.')
