--Reinitializes bank accounts balances
DELETE FROM PF_PO_INBOX;
DELETE FROM PF_PO_OUTBOX;
DELETE FROM PF_PO_FAILED;

--Log
INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'MAN', 'Delete PO.', 'Delete old PO.')
