--Reinitializes bank accounts balances
DELETE FROM PF_ACK_INBOX;
DELETE FROM PF_ACK_OUTBOX;

--Log
INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'MAN', 'Delete ACK.', 'Delete old ACK.')
