--Move from INBOX to OUTBOX and FAILED
INSERT INTO PF_PO_OUTBOX SELECT * FROM PF_PO_INBOX WHERE PO_SB_MESSAGE = 'OK';
INSERT INTO PF_PO_FAILED SELECT * FROM PF_PO_INBOX WHERE PO_SB_MESSAGE != 'OK';


--Log
INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'MAN', 'Move form INBOX', 'Move from INBOX to OUTBOX and FAILED.')
