--Process internal transactions

--SABA to SABA (Credit side)
INSERT INTO PF_BANKACCOUNTS_TRANSACTIONS (PO_ID, ACCOUNT_ID, BANK_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_PURPOSE, TRANSACTION_AMOUNT) SELECT PO_ID, DB_ACCOUNT_ID, DB_BANK_ID, TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), PO_PURPOSE, PO_AMOUNT FROM PF_PO_OUTBOX WHERE (DB_BANK_ID = 'SABA' AND SB_BANK_ID = 'SABA');

--SABA TO SABA (Debit side), notice that PO_AMOUNT is multiplied by -1, 
INSERT INTO PF_BANKACCOUNTS_TRANSACTIONS (PO_ID, ACCOUNT_ID, BANK_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_PURPOSE, TRANSACTION_AMOUNT) SELECT PO_ID, SB_ACCOUNT_ID, SB_BANK_ID, TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), PO_PURPOSE, PO_AMOUNT * -1 FROM PF_PO_OUTBOX WHERE (DB_BANK_ID = 'SABA' AND SB_BANK_ID = 'SABA');

--OTHERS TO SABA (Credit side), i.e. when others send payments to us, for this we send ACK back
INSERT INTO PF_BANKACCOUNTS_TRANSACTIONS (PO_ID, ACCOUNT_ID, BANK_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_PURPOSE, TRANSACTION_AMOUNT) SELECT PO_ID, DB_ACCOUNT_ID, DB_BANK_ID, TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), PO_PURPOSE, PO_AMOUNT FROM PF_PO_OUTBOX WHERE (DB_BANK_ID = 'SABA' AND SB_BANK_ID != 'SABA');

--Credit internal accounts, sum and substract account balances for transaction amount
UPDATE PF_BANKACCOUNTS_BALANCE SET BALANCE = (SELECT SUM(TRANSACTION_AMOUNT) FROM PF_BANKACCOUNTS_TRANSACTIONS WHERE PF_BANKACCOUNTS_BALANCE.ACCOUNT_ID = PF_BANKACCOUNTS_TRANSACTIONS.ACCOUNT_ID);

--Log
INSERT INTO PF_LOG (LOG_DATE, LOGTIME, LOG_USER, LOG_ACTION, LOG_COMMENT) VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(SYSDATE, 'HHMISS'), 'MAT', 'Process internal transactions.', 'Process internal transactions - SABA to SABA, OTHERS to SABA.')
